version: '2'
services:
  notebook:
    image: yacchin1205/lc4ri-for-public-cloud
    environment:
      TZ: Asia/Tokyo
      GRANT_SUDO: 'yes'
    user: root
    ports:
      - '127.0.0.1:8887:8888'
    working_dir: /home/jovyan
    volumes:
      - './notebooks:/home/jovyan'
      - '/var/run/docker.sock:/var/run/docker.sock'
